### ISSUE TITLE
If statement doesn't work in interface

### ISSUE THREAD

**Issue by SartoRiccardo** [turingarena/turingarena#43] opened 2018-06-30 12:33 UTC
I was testing the if statement as it was written in the guide `interface.md`. I tried to do a simple subtraction problem with the following code:
```
function subtract(a, b);

main {

	read a, b;
	if a > b {
		call c = subtract(a, b);
	} else {
		call c = subtract(b, a);
	}
	write c;

}
```
But it gave the following error as I tried to execute the `turingarena template` command:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "_main_", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/turingarena/backend/turingarena_impl/_main_.py", line 4, in <module>
    server_cli()
  File "/usr/local/turingarena/backend/turingarena_impl/cli.py", line 16, in wrapped
    fun(args, **kwargs)
  File "/usr/local/turingarena/backend/turingarena_impl/server_cli.py", line 69, in server_cli
    commands[args["<cmd>"]](argv2)
  File "/usr/local/turingarena/backend/turingarena_impl/cli.py", line 16, in wrapped
    fun(args, **kwargs)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/cli.py", line 23, in generate_template_cli
    interface = InterfaceDefinition.compile(interface_text)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/interface.py", line 40, in compile
    for msg in interface.validate():
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/interface.py", line 29, in validate
    yield from self.main_block.validate()
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/block.py", line 41, in validate
    yield from statement.validate()
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/statements/if_else.py", line 30, in validate
    yield from self.condition.validate()
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/statements/if_else.py", line 16, in condition
    return Expression.compile(self.ast.condition, self.context.expression())
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/expressions.py", line 21, in compile
    return expression_classes[ast.expression_type](ast, context)
  File "/usr/lib/python3.6/site-packages/bidict/base.py", line 410, in __getitem_
    return self._fwdm[key]
KeyError: 'comparison'
```
Before that I executed the `sudo docker pull turingarena/turingarena` and `sudo pip3 install -U turingarena-cli` commands, so I should have the most recent version of TuringArena

**Comment by cairomax** [comment] 2018-07-02 10:45
Unfortunately the comparison expression are not implemented yet.
Anyway, this interface file cannot work because TuringArena has no way to know which branch to execute when you call `subtract(a,b)` in the evaluator.
(It should report an error, but this is also not yet implemented.)
Just do
```
main {
    read a, b;
    call c = subtract(a, b);
    write c;
}
```
and make sure that `a > b` in the evalutor.
Thank you for the report.
I will close the issue when TuringArena reports correctly an error for this interface.

**Comment by alerighi** [comment] 2018-11-03 18:58
Duplicate of #64

**Closed by alerighi** 2018-11-03 18:58 UTC
