### ISSUE TITLE
Variable gives error in the interface's for loop

### ISSUE THREAD

**Issue by SartoRiccardo** [turingarena/turingarena#45] opened 2018-07-04 14:36 UTC
I was making this problem: _Given a number n, return all its divisors._ This is the code that I wrote (in order the interface, the evaluator and the solution):
```
function get_number_of_divisors(num);
procedure get_divisors(num);
function get_divisor(i);

main {

	read num;

	call n = get_number_of_divisors(num);
	call get_divisors(num);

	for i to n {
		call ans = get_divisor(i);
		write ans;
	}

}
```
```
import random
from turingarena import *

for _ in range(10):
	num = random.randint(0, 250)

	try:
		with run_algorithm(submission.source) as process:
			num_div = process.functions.get_number_of_divisors(num)
			process.procedures.get_divisors(num)
			divisors = [process.functions.get_divisor(i) for i in range(num_div)]

	# evaluating
	
	except AlgorithmError as e:
		pass
```
```
int *divisors;

int get_number_of_divisors(int num) {

	int number_of_divisors = 1;

	for(int i = 1; i <= num/2; i++) {
		if(num%i == 0) number_of_divisors++;
	}

	return number_of_divisors;

}

void get_divisors(int num) {
	divisors = new int[get_number_of_divisors(num)];
	
	int divisors_index = 0;
	for(int i = 1; i <= num; i++) {

		if (num%i == 0) {
			divisors[divisors_index] = i;
			divisors_index++;
		}

	}

}

int get_divisor(int i) {
	return divisors[i];
}
```
It gave this error:
```
Traceback (most recent call last):
  File "evaluator.py", line 17, in <module>
    num_div = process.functions.get_number_of_divisors(num)
  File "/usr/local/turingarena/libraries/python3/turingarena/driver/proxy.py", line 17, in method
    return self._engine.call(request)
  File "/usr/local/turingarena/libraries/python3/turingarena/driver/engine.py", line 43, in call
    return self.get_response_value()
  File "/usr/local/turingarena/libraries/python3/turingarena/driver/engine.py", line 55, in get_response_value
    return int(self.get_response_line())
  File "/usr/local/turingarena/libraries/python3/turingarena/driver/engine.py", line 50, in get_response_line
    assert line
AssertionError
2018-07-04 14:27:36,375    ERROR [  191] turingarena_impl.metaserver: Exception in child server.
Traceback (most recent call last):
  File "/usr/local/turingarena/backend/turingarena_impl/metaserver.py", line 91, in child_finalizer
    yield
  File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/server.py", line 41, in run_child_server
    server.run()
  File "/usr/local/turingarena/backend/turingarena_impl/driver/server.py", line 105, in run
    self.interface.run_driver(context)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/interface.py", line 69, in run_driver
    self.main_node.driver_run(context=context)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/nodes.py", line 53, in driver_run
    result = self._driver_run(context)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/block.py", line 103, in _driver_run
    result = result.merge(n.driver_run(context.extend(result)))
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/nodes.py", line 53, in driver_run
    result = self._driver_run(context)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/step.py", line 27, in _driver_run
    phase=phase,
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/step.py", line 35, in _run_children
    result = result.merge(n.driver_run(context.extend(result)))
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/nodes.py", line 53, in driver_run
    result = self._driver_run(context)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/statements/call.py", line 208, in _driver_run
    return_value = self.statement.return_value.evaluate(context.bindings)
  File "/usr/local/turingarena/backend/turingarena_impl/driver/interface/expressions.py", line 120, in evaluate
    return bindings[self.reference]
KeyError: Reference(variable=Variable(name='n', dimensions=0), index_count=0)
Traceback (most recent call last):
  File "/usr/local/turingarena/backend/turingarena_impl/driver/languages/cpp/sandbox.py", line 35, in <module>
```
To me, this seems like the only way to write this specific problem, since you need to know how many divisors _num_ has in order to return a correct array. There might be a way around this with callbacks, but I haven't tried yet.
The code seems fine to me, the evaluator makes the exact same steps as the interface. For some reason in this problem the for loop gives this error, even if in previous problems I've implemented the loop with almost exactly the same functions. I could post said problem if needed.

**Comment by SartoRiccardo** [comment] 2018-07-05 14:53
**UPDATE**
After some testing I fixed my error:
```
function get_number_of_divisors(num);
procedure get_divisors(num);
function get_divisor(i);

main {

	read num;

	call n = get_number_of_divisors(num);
        write n;

	call get_divisors(num);

	for i to n {
		call ans = get_divisor(i);
		write ans;
	}

}
```
All I had to do was insert `write n;` right after calling `get_number_of_divisors(num);`.
It feels kind of wrong, since `n` isn't one of the problem's solutions, but at least I found the problem.

**Comment by alerighi** [comment] 2018-07-05 17:52
Don't worry, it's not wrong, this is the intended behavior. When you call a function that has a return value it's required that you write the return value before calling other functions. 

This is necessary because you need to comunicate to the driver the return value of the function, otherwise it cannot resolve the associated variable (in this case, `n`) and it will die in that ugly way with a ReferenceError exception. 

Surely this kind of errors shouldn't occur at runtime, in the future we will surely improve the interface static validation checks to make sure that these errors are caught earlier so we can produce a more nice and clear diagnostic message.

**Comment by alerighi** [comment] 2018-11-03 18:58
Duplicate of #64

**Closed by alerighi** 2018-11-03 18:58 UTC
